openapi: "3.0.0"
info:
  description: .
  version: '1.0'
  title: EstadoService
  contact:
    email: marcellomrib@gmail.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: http://soa-mds/sisremocao/services/estado
paths:
  '/{codigo}':
    get:
      description: "Consulta um estado através do código IBGE"
      operationId: "consultar"
      parameters:
      - in: "path"
        name: "codigo"
        description: "código IBGE do ESTADo"
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/estado'
        '400':
          $ref: '#/components/responses/badRequest'
        '403':
          $ref: '#/components/responses/forbbiden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalError'
  '/':
    get:
      description: "Pesquisa estados disponíveis no sistema"
      operationId: pesquisar
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listaEstado'
        '400':
          $ref: '#/components/responses/badRequest'
        '403':
          $ref: '#/components/responses/forbbiden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalError'
components:
  responses:
    badRequest: 
      description: Erro de requisição
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    forbbiden:
      description: Não autorizado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    notFound:
      description: Recurso não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    internalError:
      description: O servidor não conseguiu concluir requisição
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
  schemas:
    estado:
      $ref: 'http://soa-mds/sisremocao/json/comuns/unidadeFederacaoType.json'
    listaEstado: 
      $ref: 'http://soa-mds/sisremocao/json/comuns/unidadeFederacaoListType.json'
    erro:
      $ref: 'http://soa-mds/sisremocao/json/types/erroType.json'