openapi: "3.0.0"
info:
  description: .
  version: '1.0'
  title: MunicipioService
  contact:
    email: marcellomrib@gmail.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: http://soa-mds/sisremocao/services/municipio
paths:
  '/{codigo}':
    get:
      description: "Consulta um municipio através do código IBGE"
      operationId: "consultar"
      parameters:
      - in: "path"
        name: "codigo"
        description: "código IBGE do municipio"
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/municipio'
        '400':
          $ref: '#/components/responses/badRequest'
        '403':
          $ref: '#/components/responses/forbbiden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalError'
  '/{uf}':
    get:
      description: "Pesquisa estados disponíveis no sistema"
      operationId: pesquisar
      parameters:
      - in: "path"
        name: "uf"
        description: "uf que deseja realizar listgem de municipios"
        required: true
        schema:
          type: string
          enum:
            - AC
            - AL
            - AP
            - AM
            - BA
            - CE
            - DF
            - ES
            - GO
            - MA
            - MT
            - MS
            - MG
            - PA
            - PB
            - PR
            - PE
            - PI
            - RJ
            - RN
            - RS
            - RO
            - RR
            - SC
            - SP
            - SE
            - TO
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listaMunicipio'
        '400':
          $ref: '#/components/responses/badRequest'
        '403':
          $ref: '#/components/responses/forbbiden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalError'
components:
  responses:
    badRequest: 
      description: Erro de requisição
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    forbbiden:
      description: Não autorizado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    notFound:
      description: Recurso não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    internalError:
      description: O servidor não conseguiu concluir requisição
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
  schemas:
    municipio:
      $ref: 'http://soa-mds/sisremocao/json/comuns/municipioType.json'
    listaMunicipio: 
      $ref: 'http://soa-mds/sisremocao/json/comuns/municipioListType.json'
    erro:
      $ref: 'http://soa-mds/sisremocao/json/types/erroType.json'