openapi: "3.0.0"
info:
  description: .
  version: '1.0'
  title: PessoaJuricaService
  termsOfService: 'https://ans.gov.br/soa/termos-de-uso'
  contact:
    email: soa@ans.org.br
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: http://soa-mds/pessoaJuridica
paths:
  '/{cnpj}':
    get:
      description: "Consulta uma pessoa juridica por seu CNPJ."
      operationId: "consultar"
      parameters:
      - in: "path"
        name: "cnpj"
        description: "CNPJ da pessoa jurídica"
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pessoaJuridica'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbbiden'
        '404':
          $ref: '#/components/responses/notFound'
        '406':
          $ref: '#/components/responses/notAcceptable'
        '500':
          $ref: '#/components/responses/internalError'
components:
  responses:
    badRequest: 
      description: Erro de requisição
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    unauthorized:
      description: Erro de autenticação
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    forbbiden:
      description: Não autorizado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    notFound:
      description: Recurso não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    notAcceptable:
      description: O tipo solicitado de retorno não é suportado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    internalError:
      description: O servidor não conseguiu concluir requisição
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
  schemas:
    pessoaJuridica:
      $ref: http://soa-mds/json/pessoa/pessoaJuridicaShortType.json
    erro:
      $ref: 'http://soa-mds/json/types/erroType.json'
