openapi: "3.0.0"
info:
  description: .
  version: '1.0'
  title: AmbulanciaService
  contact:
    email: marcellomrib@gmail.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: http://soa-mds/sisremocao/ambulancia
paths:
  '/{codigo}':
    get:
      description: "Consulta uma ambulancia do seu código de sistema"
      operationId: "consultar"
      parameters:
      - in: "path"
        name: "codigo"
        description: "código da ambulancia gerado pelo sistema"
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ambulancia'
        '400':
          $ref: '#/components/responses/badRequest'
        '403':
          $ref: '#/components/responses/forbbiden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalError'
    put:
      description: "Atualiza dados de uma ambulancia através do seu código de sistema"
      operationId: "atualizar"
      parameters:
      - in: "path"
        name: "codigo"
        description: "código da ambulancia gerado pelo sistema"
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ambulancia'
      responses:
        '201':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusProcessamento'
        '400':
          $ref: '#/components/responses/badRequest'
        '403':
          $ref: '#/components/responses/forbbiden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalError'
  '/':
    get:
      description: "Pesquisa por Ambulâncias através do filtros status, referente a disponibilidade"
      operationId: pesquisar
      parameters:
      - in: "query"
        name: "status"
        description: "status atual de disponibilidade da ambulância"
        required: false
        schema:
          type: string
          enum:
            - disponível
            - indsiponível
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listaAmbulancia'
        '400':
          $ref: '#/components/responses/badRequest'
        '403':
          $ref: '#/components/responses/forbbiden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalError'
    post:
      description: "Adiciona nova ambulância"
      operationId: inserir
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ambulancia'
      responses:
        '201':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusProcessamento'
        '400':
          $ref: '#/components/responses/badRequest'
        '403':
          $ref: '#/components/responses/forbbiden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalError'
    
components:
  responses:
    badRequest: 
      description: Erro de requisição
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    forbbiden:
      description: Não autorizado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    notFound:
      description: Recurso não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
    internalError:
      description: O servidor não conseguiu concluir requisição
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/erro'
  schemas:
    ambulancia:
      $ref: 'http://soa-mds/sisremocao/json/ambulancia/ambulanciaType.json'
    listaAmbulancia: 
      $ref: 'http://soa-mds/sisremocao/json/ambulancia/ambulanciaListType.json'
    erro:
      $ref: 'http://soa-mds/sisremocao/json/types/erroType.json'
    statusProcessamento:
      $ref: 'http://soa-mds/sisremocao/json/types/atributoCodificadoType.json'